name:                pantry
version:             0.1.0.0
github:              snoyberg/pantry
license:             MIT
author:              Michael Snoyman
maintainer:          michael@snoyman.com
copyright:           2018 Michael Snoyman

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/pantry#readme>

dependencies:
- base >= 4.10 && < 10
- bytestring
- conduit >= 1.3
- conduit-extra
- cryptonite
- http-conduit
- persistent
- persistent-sqlite
- persistent-template
- rio >= 0.1.3.0
- rio-orphans
- stm-chans
- tar-conduit
- word8

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

  exposed-modules:
  - Pantry

executables:
  pantry-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - pantry
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  pantry-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - pantry
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
